---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    platform: amd64
    image: ghcr.io/grokon/molecule-containers:${MOLECULE_DISTRO:-debian-trixie}
    override_command: false
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: ${MOLECULE_ANSIBLE_VERBOSITY:-0}
scenario:
  test_sequence:
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
verifier:
  name: ansible
